version: "3"

services:
  web-node-js:
    image: myregistry.local:5000/mayjk23/demo-nodejs
    restart: always
    ports:
      - "3000:3000"
    environment:
      - MONGODB_ADDON_URI=mongodb://mongodb:27017/test
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
